# Generated by Django 5.2.2 on 2025-06-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryBeatTask_UTT',
            fields=[
                ('celery_beat_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=255)),
                ('chat_name', models.CharField(max_length=255)),
                ('host_id', models.CharField(max_length=255)),
                ('sharepoint_path', models.CharField(max_length=1024)),
                ('display_path', models.CharField(max_length=1024)),
                ('frequency_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('result_question_ls', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
