# Generated by Django 5.2.2 on 2025-06-16 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('drive_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('notify_interval', models.IntegerField(default=60)),
                ('last_notified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('next_notify_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('host_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('drive_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('teams_group_id', models.CharField(max_length=255)),
                ('teams_group_name', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('task', models.CharField(max_length=255)),
                ('owner_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('owner_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('owner_name', models.CharField(blank=True, default='Unknown Owner', max_length=255, null=True)),
                ('field_address', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('msg_id', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_id', models.CharField(max_length=255)),
            ],
        ),
    ]
