# Generated by Django 5.2.2 on 2025-07-15 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_taskmanager_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='id',
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
