# Generated by Django 5.2.2 on 2025-08-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remove_taskmanager_id_alter_taskmanager_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='sheet_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
