# Generated by Django 5.2.2 on 2025-08-06 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('reminders', '0004_taskmanager_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
