FROM python:3.12-slim

WORKDIR /app
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["/entrypoint.sh"]