app_id:
app_secret:
redirect:
scopes:
  - user.read
  - user.readbasic.all
  - mailboxsettings.read
  - calendars.readwrite
  - calendars.read.shared
  - chat.read
  - chat.readwrite
  - Files.Read
  - Sites.Read.All
  - Files.ReadWrite.All
  - Sites.ReadWrite.All
authority: "https://login.microsoftonline.com/common"
GEMINI_API_KEY: 